### ISSUE TITLE
Zurich is in Switzerland, not Germany

### ISSUE THREAD

**Issue by derickr** [JodaOrg/global-tz#4]
The `actions.txt` file lists:

```
# Europe/Busingen (DE) links to Europe/Zurich (DE)
# No need to change anything as both are in DE and data is the same since 1970
```

`Europe/Zurich` is not in Germany, it is in Switzerland.

**Comment by rkraneis** [comment]
Büsingen is a German exclave in Switzerland and observed Swiss DST: https://en.wikipedia.org/wiki/B%C3%BCsingen_am_Hochrhein#Time_zone

**Comment by jodastephen** [comment]
This is just a badly worded comment, which needs fixing. The data is correct.

**Comment by derickr** [comment]
Yes, sorry if I wasn't clear. It's the comment that's confusing, not the data which is indeed correct.

**Comment by jodastephen** [comment]
Fixed thanks
