### ISSUE TITLE
Fix global-tz for 2022b

### ISSUE THREAD

**Issue by jodastephen** [JodaOrg/global-tz#5]
Update to handle 2022b changes. Ensure it matches the PACKRATLIST option

**Comment by hagai-lvi** [comment]
Hello @jodastephen 
Do you expect to attend to this and https://github.com/JodaOrg/joda-time/issues/621 soon?

I would appreciate any information.
Thank you!

**Comment by jodastephen** [comment]
This has already been done, sorry I didn't close this
